"""
OpenHands workspace isolation configuration.

Phase 2.3 removed the old BrowserAI-side Docker remount hack. BrowserAI no
longer needs docker.sock or docker-cli. OpenHands remains the only service that
creates runtime containers; it receives a config.toml with a workspace bind:

    [sandbox]
    volumes = "<host-workspace-root>:/workspace:rw"

BrowserAI still scopes all UI file APIs to /workspace/chats/<chat_id> and the
agent prompt instructs OpenHands to work only inside that per-chat subdirectory.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path

log = logging.getLogger("browserai.isolation")

DATA_DIR = os.environ.get("BROWSERAI_DATA_DIR") or "/data"
CONFIG_PATH = Path(os.environ.get("BROWSERAI_OPENHANDS_CONFIG") or os.path.join(DATA_DIR, "oh-config.toml"))
CONTAINER_WORKSPACE_ROOT = Path(os.environ.get("WORKSPACE_ROOT") or "/workspace")
HOST_WORKSPACE_ROOT = os.environ.get(
    "BROWSERAI_HOST_WORKSPACE_ROOT"
    ) or os.environ.get("WORKSPACE_DIR") or os.path.join(os.environ.get("DATA_DIR", "/opt/browserai-data"), "workspace")
SANDBOX_DIR = CONTAINER_WORKSPACE_ROOT / "_sandbox"
USE_LEGACY_ISOLATION = os.environ.get("BROWSERAI_USE_ISOLATION", "0").lower() in {"1", "true", "yes", "on"}


def _toml_quote(value: str) -> str:
    return '"' + str(value).replace('\\', '\\\\').replace('"', '\\"') + '"'


def ensure_sandbox_dir() -> str:
    """Ensure BrowserAI's mounted workspace root exists inside this container."""
    CONTAINER_WORKSPACE_ROOT.mkdir(parents=True, exist_ok=True)
    SANDBOX_DIR.mkdir(parents=True, exist_ok=True)
    return str(SANDBOX_DIR)


def desired_sandbox_volumes() -> str:
    """Host path used by OpenHands when it creates runtime containers."""
    return f"{HOST_WORKSPACE_ROOT}:/workspace:rw"


def ensure_openhands_config() -> str:
    """Create/update OpenHands config.toml for config-based workspace mounting.

    The file is mounted into the OpenHands service. OpenHands reads it on
    startup and passes sandbox.volumes to each runtime container. We keep this
    minimal to avoid overwriting settings managed through OpenHands /api/settings.
    """
    ensure_sandbox_dir()
    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    volumes = desired_sandbox_volumes()
    content = (
        "# Generated by BrowserAI Phase 2.3.\n"
        "# BrowserAI must not remount runtime containers directly.\n"
        "[sandbox]\n"
        f"volumes = {_toml_quote(volumes)}\n"
    )
    current = CONFIG_PATH.read_text(encoding="utf-8") if CONFIG_PATH.exists() else ""
    if current != content:
        CONFIG_PATH.write_text(content, encoding="utf-8")
        log.info("OpenHands config updated: %s sandbox.volumes=%s", CONFIG_PATH, volumes)
    return str(CONFIG_PATH)


async def remount_runtime_async(conversation_id: str, chat_id: str) -> bool:
    """Deprecated compatibility shim.

    The old implementation used docker inspect/stop/rm/create from inside the
    BrowserAI container. Phase 2.3 intentionally disables that path. Callers may
    keep awaiting this function during transition; it only ensures config exists.
    """
    ensure_openhands_config()
    if USE_LEGACY_ISOLATION:
        log.warning(
            "BROWSERAI_USE_ISOLATION=1 requested for cid=%s chat_id=%s, but "
            "legacy Docker remount is removed. Using config.toml isolation instead.",
            conversation_id,
            chat_id,
        )
    return True
